export interface NPCTemplate {
  id: string;
  archetype: string;
  name_pool: string[];
  location_types: string[];
  spawn_weight: number;
  relationship_start: [number, number]; // [min, max] disposition
  personality: {
    ambition: number;
    loyalty: number;
    fear: number;
  };
  has_quest: boolean;
  role: string;
  base_stats: {
    hp_max: number;
    ac: number;
    attack_bonus: number;
    damage_dice: string;
    damage_modifier: number;
  };
  short_term_goal?: string;
  long_term_goal?: string;
  secret?: string;
}

export const NPC_TEMPLATES: NPCTemplate[] = [
  {
    id: "wandering_merchant",
    archetype: "merchant",
    name_pool: ["Gareth", "Sable", "Piotr", "Nessa"],
    location_types: ["village", "wilderness", "city"],
    spawn_weight: 8,
    relationship_start: [50, 60],
    personality: { ambition: 70, loyalty: 20, fear: 40 },
    has_quest: true,
    role: "Wandering Merchant",
    base_stats: { hp_max: 12, ac: 10, attack_bonus: 2, damage_dice: "1d4", damage_modifier: 0 },
    short_term_goal: "Sell out current stock of exotic goods",
    long_term_goal: "Establish a permanent shop in the capital city",
    secret: "Smuggles illegal drugs under the cover of exotic spices"
  },
  {
    id: "tavern_keeper",
    archetype: "merchant",
    name_pool: ["Barnaby", "Gideon", "Maeve", "Hestia"],
    location_types: ["village", "city"],
    spawn_weight: 10,
    relationship_start: [50, 70],
    personality: { ambition: 50, loyalty: 60, fear: 30 },
    has_quest: true,
    role: "Tavern Keeper",
    base_stats: { hp_max: 20, ac: 11, attack_bonus: 3, damage_dice: "1d6", damage_modifier: 1 },
    short_term_goal: "Resolve the supply shortage of dwarven ale",
    long_term_goal: "Retire comfortably and pass the tavern to their child",
    secret: "The tavern basement holds a hidden escape route used by the local thieves' guild"
  },
  {
    id: "local_guard",
    archetype: "protector",
    name_pool: ["Jeremy", "Varis", "Kaelen", "Lyra"],
    location_types: ["village", "city"],
    spawn_weight: 9,
    relationship_start: [40, 60],
    personality: { ambition: 40, loyalty: 70, fear: 50 },
    has_quest: false,
    role: "Town Guard",
    base_stats: { hp_max: 16, ac: 14, attack_bonus: 4, damage_dice: "1d8", damage_modifier: 2 },
    short_term_goal: "Survive the night patrol without incident",
    long_term_goal: "Get promoted to Guard Captain",
    secret: "Accepts minor bribes to look the other way after curfew"
  },
  {
    id: "guard_captain",
    archetype: "protector",
    name_pool: ["Captain Vance", "Captain Ronald", "Captain Sterling", "Captain Keth"],
    location_types: ["village", "city"],
    spawn_weight: 3,
    relationship_start: [40, 50],
    personality: { ambition: 60, loyalty: 80, fear: 20 },
    has_quest: true,
    role: "Guard Captain",
    base_stats: { hp_max: 32, ac: 16, attack_bonus: 5, damage_dice: "1d8", damage_modifier: 3 },
    short_term_goal: "Root out faction spies within the town guard",
    long_term_goal: "Bring absolute law and order to the entire province",
    secret: "Accidentally allowed a notorious criminal to escape years ago and framed someone else"
  },
  {
    id: "shady_informant",
    archetype: "rogue",
    name_pool: ["Sly", "Fingers", "Whisper", "Shadow"],
    location_types: ["city", "wilderness"],
    spawn_weight: 6,
    relationship_start: [30, 50],
    personality: { ambition: 80, loyalty: 10, fear: 60 },
    has_quest: true,
    role: "Informant",
    base_stats: { hp_max: 14, ac: 12, attack_bonus: 4, damage_dice: "1d6", damage_modifier: 2 },
    short_term_goal: "Obtain a copy of the noble faction's correspondence",
    long_term_goal: "Gain enough blackmail material to live in luxury",
    secret: "Double-crosses clients constantly and sells information to the highest bidder"
  },
  {
    id: "hedge_mage",
    archetype: "scholar",
    name_pool: ["Elidon", "Zephyr", "Althea", "Pythor"],
    location_types: ["wilderness", "village", "city"],
    spawn_weight: 5,
    relationship_start: [40, 60],
    personality: { ambition: 75, loyalty: 40, fear: 45 },
    has_quest: true,
    role: "Hedge Mage",
    base_stats: { hp_max: 18, ac: 11, attack_bonus: 4, damage_dice: "1d6", damage_modifier: 2 },
    short_term_goal: "Gather rare phosphorescent mushrooms from the wilds",
    long_term_goal: "Discover a brand new spell formula to cement their legacy",
    secret: "Banished from the High Academy for researching forbidden necromancy spells"
  },
  {
    id: "temple_priest",
    archetype: "scholar",
    name_pool: ["Brother Peter", "Sister Martha", "Father Joseph", "Mother Teresa"],
    location_types: ["village", "city"],
    spawn_weight: 7,
    relationship_start: [50, 70],
    personality: { ambition: 30, loyalty: 80, fear: 30 },
    has_quest: true,
    role: "Priest",
    base_stats: { hp_max: 15, ac: 10, attack_bonus: 3, damage_dice: "1d4", damage_modifier: 0 },
    short_term_goal: "Organize the local festival of light",
    long_term_goal: "Purify the ancient defiled temple in the depths",
    secret: "Silently questioning their faith after witnessing a dark omen"
  },
  {
    id: "farm_hand",
    archetype: "laborer",
    name_pool: ["Toby", "Giles", "Pip", "Jenny"],
    location_types: ["village", "wilderness"],
    spawn_weight: 9,
    relationship_start: [50, 60],
    personality: { ambition: 30, loyalty: 50, fear: 60 },
    has_quest: false,
    role: "Farm Hand",
    base_stats: { hp_max: 10, ac: 10, attack_bonus: 2, damage_dice: "1d4", damage_modifier: 1 },
    short_term_goal: "Finish the harvest before the storm hits",
    long_term_goal: "Own a small plot of farm land",
    secret: "Witnessed a cult meeting in the fields but is too terrified to tell anyone"
  },
  {
    id: "blacksmith",
    archetype: "artisan",
    name_pool: ["Iron-Breaker", "Thorin", "Grigor", "Martha"],
    location_types: ["village", "city"],
    spawn_weight: 8,
    relationship_start: [50, 60],
    personality: { ambition: 40, loyalty: 70, fear: 20 },
    has_quest: true,
    role: "Blacksmith",
    base_stats: { hp_max: 24, ac: 12, attack_bonus: 4, damage_dice: "1d8", damage_modifier: 2 },
    short_term_goal: "Acquire high-quality iron ore",
    long_term_goal: "Forge a masterpiece sword worthy of a king",
    secret: "Secretly crafts weapons for the rebel faction out of fear or sympathy"
  },
  {
    id: "herbalist",
    archetype: "scholar",
    name_pool: ["Rowan", "Sage", "Clover", "Willow"],
    location_types: ["village", "wilderness"],
    spawn_weight: 8,
    relationship_start: [50, 70],
    personality: { ambition: 40, loyalty: 60, fear: 40 },
    has_quest: true,
    role: "Herbalist",
    base_stats: { hp_max: 12, ac: 10, attack_bonus: 2, damage_dice: "1d4", damage_modifier: 0 },
    short_term_goal: "Prepare healing salves for the wounded guards",
    long_term_goal: "Find a cure for the rotting blight affecting the crops",
    secret: "Can brew deadly poisons, keeping a secret ledger of who purchases them"
  },
  {
    id: "city_noble",
    archetype: "noble",
    name_pool: ["Lord Byron", "Lady Eleanor", "Lord Percival", "Lady Beatrice"],
    location_types: ["city"],
    spawn_weight: 4,
    relationship_start: [30, 40],
    personality: { ambition: 90, loyalty: 30, fear: 30 },
    has_quest: true,
    role: "Noble",
    base_stats: { hp_max: 18, ac: 12, attack_bonus: 3, damage_dice: "1d6", damage_modifier: 1 },
    short_term_goal: "Gain the favor of the governor",
    long_term_goal: "Depose the current ruler and take their seat",
    secret: "Financially supporting the syndicate to destabilize rival nobles"
  },
  {
    id: "beggar",
    archetype: "outcast",
    name_pool: ["Whiskers", "Old Pete", "Ragged Ann", "Blind Joe"],
    location_types: ["city", "village"],
    spawn_weight: 8,
    relationship_start: [40, 60],
    personality: { ambition: 20, loyalty: 40, fear: 70 },
    has_quest: false,
    role: "Beggar",
    base_stats: { hp_max: 8, ac: 10, attack_bonus: 1, damage_dice: "1d4", damage_modifier: 0 },
    short_term_goal: "Find warm shelter and enough food for tonight",
    long_term_goal: "Survive the winter",
    secret: "Hears almost everything discussed in the city streets and acts as a spy for the thieves' guild"
  },
  {
    id: "bounty_hunter",
    archetype: "hunter",
    name_pool: ["Jax", "Vesper", "Silas", "Kael"],
    location_types: ["wilderness", "city"],
    spawn_weight: 5,
    relationship_start: [30, 50],
    personality: { ambition: 70, loyalty: 50, fear: 10 },
    has_quest: true,
    role: "Bounty Hunter",
    base_stats: { hp_max: 28, ac: 14, attack_bonus: 5, damage_dice: "1d8", damage_modifier: 2 },
    short_term_goal: "Track down the fugitive hiding in the swamps",
    long_term_goal: "Claim the massive bounty on a faction warlord",
    secret: "Occasionally takes assassinations under the guise of bounty collection"
  },
  {
    id: "cult_recruit",
    archetype: "fanatic",
    name_pool: ["Malakar", "Vora", "Xandros", "Lyzette"],
    location_types: ["dungeon", "wilderness"],
    spawn_weight: 4,
    relationship_start: [10, 20],
    personality: { ambition: 80, loyalty: 90, fear: 40 },
    has_quest: false,
    role: "Cult Recruit",
    base_stats: { hp_max: 15, ac: 11, attack_bonus: 3, damage_dice: "1d6", damage_modifier: 1 },
    short_term_goal: "Assist the high priest in the summoning ritual",
    long_term_goal: "Earn a high rank and receive the entity's direct blessing",
    secret: "Is secretly plotting to overthrow the high priest to take control of the cult"
  },
  {
    id: "mercenary_recruit",
    archetype: "soldier",
    name_pool: ["Bruiser", "Spike", "Blade", "Hammer"],
    location_types: ["wilderness", "city"],
    spawn_weight: 6,
    relationship_start: [30, 50],
    personality: { ambition: 60, loyalty: 40, fear: 30 },
    has_quest: true,
    role: "Mercenary",
    base_stats: { hp_max: 22, ac: 13, attack_bonus: 4, damage_dice: "1d8", damage_modifier: 2 },
    short_term_goal: "Secure a highly paid escort contract",
    long_term_goal: "Start their own mercenary guild company",
    secret: "Will break any contract if offered triple the gold by the enemy faction"
  },
  {
    id: "guild_leader",
    archetype: "leader",
    name_pool: ["Master Corvus", "Mistress Vane", "Guildmaster Jax", "Lady Sterling"],
    location_types: ["city"],
    spawn_weight: 2,
    relationship_start: [40, 50],
    personality: { ambition: 85, loyalty: 50, fear: 30 },
    has_quest: true,
    role: "Guild Leader",
    base_stats: { hp_max: 35, ac: 14, attack_bonus: 5, damage_dice: "1d6", damage_modifier: 3 },
    short_term_goal: "Secure the guild's trade monopoly with the local barony",
    long_term_goal: "Infiltrate the royal council and control trade policy",
    secret: "Uses guild funds to finance pirate raids on rival trade ships"
  },
  {
    id: "town_crier",
    archetype: "messenger",
    name_pool: ["Pip", "Billy", "Ned", "Sally"],
    location_types: ["city", "village"],
    spawn_weight: 6,
    relationship_start: [50, 60],
    personality: { ambition: 40, loyalty: 50, fear: 50 },
    has_quest: false,
    role: "Town Crier",
    base_stats: { hp_max: 10, ac: 10, attack_bonus: 1, damage_dice: "1d4", damage_modifier: 0 },
    short_term_goal: "Deliver the crown announcements clearly",
    long_term_goal: "Leave the city and find a quiet place to write memoirs",
    secret: "Spreads fake rumours for a small coin to manipulate local merchant prices"
  },
  {
    id: "street_urchin",
    archetype: "rogue",
    name_pool: ["Picker", "Dodger", "Skip", "Flick"],
    location_types: ["city"],
    spawn_weight: 7,
    relationship_start: [40, 60],
    personality: { ambition: 50, loyalty: 40, fear: 60 },
    has_quest: true,
    role: "Street Urchin",
    base_stats: { hp_max: 8, ac: 12, attack_bonus: 3, damage_dice: "1d4", damage_modifier: 1 },
    short_term_goal: "Steal enough food or coin for the urchin pack",
    long_term_goal: "Escape the slums and become a respected merchant",
    secret: "Stole a noble's signet ring and is hiding it in a hollow brick in the alley"
  },
  {
    id: "foreign_diplomat",
    archetype: "noble",
    name_pool: ["Ambassador Kael", "Envoy Beatrice", "Baron Von Strum", "Countess Lisa"],
    location_types: ["city"],
    spawn_weight: 2,
    relationship_start: [30, 40],
    personality: { ambition: 70, loyalty: 70, fear: 40 },
    has_quest: true,
    role: "Diplomat",
    base_stats: { hp_max: 16, ac: 11, attack_bonus: 2, damage_dice: "1d4", damage_modifier: 0 },
    short_term_goal: "Negotiate a ceasefire or trade pact",
    long_term_goal: "Annex this territory for their homeland without war",
    secret: "Mapping the city fortifications for a planned invasion force"
  },
  {
    id: "retired_adventurer",
    archetype: "soldier",
    name_pool: ["Old Greg", "Iron-Side", "Daring Dan", "Valda"],
    location_types: ["village", "wilderness"],
    spawn_weight: 5,
    relationship_start: [50, 70],
    personality: { ambition: 20, loyalty: 60, fear: 10 },
    has_quest: true,
    role: "Retired Adventurer",
    base_stats: { hp_max: 30, ac: 13, attack_bonus: 5, damage_dice: "1d8", damage_modifier: 3 },
    short_term_goal: "Recover a stolen family shield from the goblins",
    long_term_goal: "Keep the village safe from the ancient evil returning",
    secret: "The sole survivor of a failed quest that woke up the ancient threat in the Ashen Gate"
  },
  {
    id: "mine_worker",
    archetype: "laborer",
    name_pool: ["Grunt", "Flint", "Rusty", "Stony"],
    location_types: ["wilderness", "village"],
    spawn_weight: 7,
    relationship_start: [40, 60],
    personality: { ambition: 40, loyalty: 50, fear: 50 },
    has_quest: false,
    role: "Miner",
    base_stats: { hp_max: 14, ac: 11, attack_bonus: 3, damage_dice: "1d6", damage_modifier: 1 },
    short_term_goal: "Hit a rich vein of silver ore",
    long_term_goal: "Buy their way out of the mining contract",
    secret: "Found a glowing dark crystal deep in the shaft and has been carrying it in their pocket"
  },
  {
    id: "local_sheriff",
    archetype: "protector",
    name_pool: ["Sheriff Miller", "Sheriff Vance", "Sheriff Dale", "Sheriff Knox"],
    location_types: ["village"],
    spawn_weight: 4,
    relationship_start: [40, 60],
    personality: { ambition: 45, loyalty: 75, fear: 40 },
    has_quest: true,
    role: "Sheriff",
    base_stats: { hp_max: 26, ac: 14, attack_bonus: 4, damage_dice: "1d8", damage_modifier: 2 },
    short_term_goal: "Apprehend the thieves who raided the farmhouses",
    long_term_goal: "Live out their days in a peaceful, crime-free town",
    secret: "Is closely related to the leader of the local gang of outlaws"
  },
  {
    id: "smuggler",
    archetype: "rogue",
    name_pool: ["Swift", "Cargo", "Slick", "Breeze"],
    location_types: ["wilderness", "city"],
    spawn_weight: 6,
    relationship_start: [30, 50],
    personality: { ambition: 75, loyalty: 40, fear: 40 },
    has_quest: true,
    role: "Smuggler",
    base_stats: { hp_max: 16, ac: 13, attack_bonus: 4, damage_dice: "1d6", damage_modifier: 2 },
    short_term_goal: "Transport a carriage of contraband past the checkpoints",
    long_term_goal: "Retire with a clean slate and open a legitimate shipping fleet",
    secret: "Currently carrying a list of names of corrupted city guards"
  },
  {
    id: "scholar_apprentice",
    archetype: "scholar",
    name_pool: ["Timmy", "Leo", "Penny", "Cleo"],
    location_types: ["city", "village"],
    spawn_weight: 7,
    relationship_start: [50, 70],
    personality: { ambition: 65, loyalty: 60, fear: 50 },
    has_quest: true,
    role: "Apprentice Scholar",
    base_stats: { hp_max: 10, ac: 10, attack_bonus: 2, damage_dice: "1d4", damage_modifier: 0 },
    short_term_goal: "Translate the ancient parchment scroll correctly",
    long_term_goal: "Become a high wizard's personal archivist",
    secret: "Accidentally destroyed a valuable book and is trying to find a replacement before being discovered"
  },
  {
    id: "hermit",
    archetype: "outcast",
    name_pool: ["Father Time", "Greybeard", "Solitude", "Elder Moss"],
    location_types: ["wilderness"],
    spawn_weight: 3,
    relationship_start: [40, 60],
    personality: { ambition: 10, loyalty: 50, fear: 30 },
    has_quest: true,
    role: "Hermit",
    base_stats: { hp_max: 14, ac: 10, attack_bonus: 2, damage_dice: "1d4", damage_modifier: 0 },
    short_term_goal: "Gather herbs for winter hibernation prep",
    long_term_goal: "Attain spiritual enlightenment in solitude",
    secret: "Possesses a map showing the exact location of the lost vault of the dragon lords"
  },
  {
    id: "street_performer",
    archetype: "bard",
    name_pool: ["Jester", "Strings", "Flute", "Harper"],
    location_types: ["city"],
    spawn_weight: 6,
    relationship_start: [45, 65],
    personality: { ambition: 60, loyalty: 50, fear: 40 },
    has_quest: false,
    role: "Performer",
    base_stats: { hp_max: 12, ac: 11, attack_bonus: 3, damage_dice: "1d6", damage_modifier: 1 },
    short_term_goal: "Collect enough gold from the town square tips",
    long_term_goal: "Perform in the royal court hall",
    secret: "Is a spy hired by a rival city to gauge local military morale"
  },
  {
    id: "grave_digger",
    archetype: "laborer",
    name_pool: ["Bones", "Shovel", "Spade", "Mortimer"],
    location_types: ["village", "city"],
    spawn_weight: 5,
    relationship_start: [40, 50],
    personality: { ambition: 30, loyalty: 60, fear: 40 },
    has_quest: true,
    role: "Grave Digger",
    base_stats: { hp_max: 18, ac: 11, attack_bonus: 3, damage_dice: "1d6", damage_modifier: 1 },
    short_term_goal: "Prepare the graves for recent combat casualties",
    long_term_goal: "Uncover why corpses are rising in the local cemetery",
    secret: "Robs the graves of wealthy nobles before filling them with dirt"
  },
  {
    id: "watchtower_sentry",
    archetype: "protector",
    name_pool: ["Hawkeye", "Eagle", "Sentry Cole", "Sentry Ward"],
    location_types: ["wilderness", "village"],
    spawn_weight: 6,
    relationship_start: [40, 60],
    personality: { ambition: 40, loyalty: 70, fear: 40 },
    has_quest: false,
    role: "Sentry",
    base_stats: { hp_max: 15, ac: 13, attack_bonus: 4, damage_dice: "1d8", damage_modifier: 1 },
    short_term_goal: "Spot any incoming goblin scouts or nemeses",
    long_term_goal: "Return to the capital to serve in the honor guard",
    secret: "Fell asleep on watch when a minor raid occurred and hid the evidence"
  },
  {
    id: "tavern_waitress",
    archetype: "laborer",
    name_pool: ["Sally", "Molly", "Daisy", "Rose"],
    location_types: ["village", "city"],
    spawn_weight: 8,
    relationship_start: [50, 70],
    personality: { ambition: 50, loyalty: 55, fear: 50 },
    has_quest: false,
    role: "Waitress",
    base_stats: { hp_max: 10, ac: 10, attack_bonus: 1, damage_dice: "1d4", damage_modifier: 0 },
    short_term_goal: "Collect all tips and clean the tables before closing",
    long_term_goal: "Save enough gold to purchase their own trade wagon",
    secret: "Knows which local official is secretly meeting with the shadow syndicate"
  },
  {
    id: "suspicious_stranger",
    archetype: "cultist",
    name_pool: ["Hooded One", "Cloaked Figure", "Veil", "Shadow-Walker"],
    location_types: ["wilderness", "city", "dungeon"],
    spawn_weight: 4,
    relationship_start: [20, 30],
    personality: { ambition: 80, loyalty: 80, fear: 35 },
    has_quest: true,
    role: "Mysterious Stranger",
    base_stats: { hp_max: 20, ac: 12, attack_bonus: 4, damage_dice: "1d6", damage_modifier: 2 },
    short_term_goal: "Deliver the dark offering to the designated location",
    long_term_goal: "Infiltrate the city council for the shadow order",
    secret: "Is carrying the ritual parchment that details how to summon the archnemesis"
  }
];
